name: UCD
version: '1.0.0'
license: MIT
author: Tristan Seligmann
maintainer: mithrandi@mithrandi.net
copyright: © 2015 Tristan Seligmann
dependencies:
  - protolude >=0.1.6 && <0.3
library:
  source-dirs:
    - src
  dependencies:
    - base >=4 && <5
    - aeson
    - bytestring
    - clock
    - containers
    - hexpat
    - http-api-data
    - http-types
    - lens
    - monad-control
    - monad-logger
    - persistent
    - persistent-sqlite
    - persistent-template
    - prometheus-client >=0.2.0
    - prometheus-metrics-ghc
    - resource-pool
    - servant
    - servant-server
    - servant-swagger
    - servant-swagger-ui
    - swagger2
    - text
    - unordered-containers
    - wai
    - wai-extra
    - wai-middleware-prometheus
    - warp
  default-extensions:
    - CPP
    - DataKinds
    - DeriveDataTypeable
    - DeriveGeneric
    - EmptyDataDecls
    - FlexibleContexts
    - FlexibleInstances
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MultiParamTypeClasses
    - NoImplicitPrelude
    - NoMonomorphismRestriction
    - OverloadedStrings
    - PartialTypeSignatures
    - QuasiQuotes
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeFamilies
    - TypeOperators
    - ViewPatterns
  ghc-options:
    - -Wall
    - -O2
executables:
  ucdapi:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -Wall
      - -threaded
      - -O2
      - -rtsopts
      - '"-with-rtsopts=-N -T"'
    dependencies:
      - base
      - UCD
