resolver: lts-8.20
packages:
- '.'
extra-deps:
- hexpat-lens-0.1.5
- hexpat-tagsoup-0.1
image:
  container:
    name: idnar/ucdapi
    base: fpco/stack-minrun
    add:
      db: /db
    entrypoints:
      - ucdapi
      - loaddata
